### ISSUE TITLE
Financial Dashboard Research

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#11]
- [x] Find free or low cost dashboard display solution.
- [x] Get association code from SEE and download.

Research nonprofit financial dashboard.
@myamakerspace wants a way to be able to get certain information seen at a glance in a smart way where the computer pulls info from difference sheets and does the computation for you.

**Comment by nedventures** [comment]
Smartsheet came up with sight gallery.
Pending information about that from @myamakerspace

**Comment by myamakerspace** [comment]
They won't give us a discount so I gotta try and find something cheaper :( I don't want to pay $500 for a single function that sucks ass.

**Comment by myamakerspace** [comment]
Tableau is free for nonprofits  http://www.tableaufoundation.org/initiatives/tableau-non-profits

**Comment by myamakerspace** [comment]
Once we have signed up, they have volunteers who will teach us the program
https://servicecorps.tableaufoundation.org/

**Comment by myamakerspace** [comment]
Emailed SEE again.

**Comment by nedventures** [comment]
Status on this?
Or can we just start implementing and getting the training?
