### ISSUE TITLE
Meltdown Comics Next Workshop Ideas

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#15]
What workshop can we host?
We have Janean, Leiny, and Malakai who are able to host a workshop.
Any ideas?

**Comment by myamakerspace** [comment]
A volunteer signed up who does "Science Magic," I've reached out to her, and Sara is talking to a "Little Makers" person for me. Once i hear back from those two let's set the next 3. Ideally I'd like to do a Little Makers next.

**Comment by nedventures** [comment]
Perfect! That sounds cool.
At the EdTech thing I met this guy who can do Scratch and integrate a green screen and god knows what else he told me. I'm scheduling a call so we can discuss further details.

**Comment by myamakerspace** [comment]
Science Magic volunteer said she can do it, finding out what exactly she's doing, then
- [ ] check if it's OK with meltdown

**Comment by nedventures** [comment]
# Saturday, May 14 : John with Virtual Gaming

### Materials Needed
- [x] laptops
- [x] projector
- [x] white cover for screen? don't we have a screen in storage? (ned, check please)
- [x] hotspots
- [x] extension cords

### To Do
- [x] Confirm attendance
- [x] Write Blurb about class
- [x] Mya proofread
- [x] send to Meltdown
- [x] make eventbrite for RSVPs: state that $ is paid at the door

**Comment by myamakerspace** [comment]
Hurrah! I need info for blurb now - What is this exactly

**Comment by nedventures** [comment]
@myamakerspace this is what he emailed me before you asked him about it: I'm definitely down to do this class. It's on my calendar and I'm ready to go. You can probably call it something like "fundamentals of game design" or something more fun if you'd like. The premise would simply be a very gentle introduction to programming and game design. It should be very fitting for any age and basic skill level. 3 hours sounds pretty solid.

**Comment by myamakerspace** [comment]
Ned also need to add "make eventbrite for RSVPs" into the sequence as well as "writer blurb" For future ones.

For now -- Please make eventbrite

**Comment by myamakerspace** [comment]
I would like each workshop to be its own issue. This issue was for getting the next 3 scheduled. We could check off #1 at this point but still know we need 2 more. Then once we have checked off those-- The next 3 come up immediately.
