### ISSUE TITLE
Coding Crew Program Coordinator

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#17]
- [x] write job description
- [ ] recruit
- [ ] hire

**Comment by nedventures** [comment]
EdSurge led to a potential CompCodCrw Coordinator: Enok Kim

**Comment by myamakerspace** [comment]
Enok passed screening interview, send on to Brian

**Comment by nedventures** [comment]
Sent to Brian.
Awaiting response.

**Comment by myamakerspace** [comment]
If you don't hear from him by tomorrow morning pls text.
