### ISSUE TITLE
Present at Cal STEM

### ISSUE THREAD

**Issue by myamakerspace** [LAMakerspace/ToDo#36]
- [x] Check with Tara if she is
- [x] application: http://stemcalifornia.org/presenters

**Comment by myamakerspace** [comment]
tara's cool wit it

**Comment by tarabrown** [comment]
what is the topic you are presenting? so if i decide im going to make a proposal ill do something different

**Comment by myamakerspace** [comment]
Equity, how leveraging infrastructure that is already there can make a
major impact on the digital divide

Mya Stark
Director
LA Makerspace
310-463-5296
www.lamakerspace.com
https://twitter.com/lamakerspace
https://www.facebook.com/LAMakerspace
https://instagram.com/lamakerspace/

On Fri, Apr 29, 2016 at 11:49 AM, Tara Tiger Brown <notifications@github.com
