### ISSUE TITLE
3D Doodler Pen Defective

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#44]
- [x] Eain to write up problems with pen
- [x] submit inquiry
- [x] pending actions

**Comment by myamakerspace** [comment]
What the dick

**Comment by nedventures** [comment]
Responded, they want to google chat. I sent the email to Eain to schedule a video chat, if troubleshooting doesn't work they will send a new one.

**Comment by nedventures** [comment]
Sent in our info to be sent in a new 3Doodler Pen.
