### ISSUE TITLE
May 17th Board Meeting Prep

### ISSUE THREAD

**Issue by myamakerspace** [LAMakerspace/ToDo#47]
Agenda Item Brainstorm:
- Case for immediately raising operating reserve 
- Strategic and Action Plans
- Annenberg Learnings
- Meet Lee Ann Wong, Meet Janne
- Vote on Lee Ann and Joe
- Vote Malik for President
- Would the board accept money from Chevron?
- Ned's and my job descriptions
- Budget
- [x] Draft Agenda
- [x] Draft any resolutions
- Create materials packets
  - [x] Adapt Hellen's Board Ambassador packet to us
- [x] Resumes of Guests
- [x] Circulate Agenda by Monday the 16th

**Comment by nedventures** [comment]
- [ ] research vegan pizza options nearby
- [ ] purchase snacks such as:
- nuts
- cookies
- muffins
- chips
- veggies?
