### ISSUE TITLE
Community Impact Arts Grant Program TO DO

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#48]
- [x] ensure LA County grant funds do NOT exceed 50% of the total cost of the supported project.
- @myamakerspace to do the adjustment budget matching sheet
- [x] Signing the contract 
- [ ] recognize support from LA County by placing logo and credit line on LAM's printed materials and website
- @myamakerspace TO DO
- [x] registered to do business in CA an in good standing with CA Secretary of State
- Marvin
- [x] have a current vendor number registered with LA county
  -Marvin
- [x] enroll in Direct Deposit
- Marvin
- [x] have a DUNS number 
- Marvin
- [x] send a letter of acknowledgement from executive director, board chair, or both, thanking the Board of Supervisors for the grant (providing details regarding CIAG project and its impact in your community)

**Comment by myamakerspace** [comment]
_ensure LA County grant funds do NOT exceed 50% of the total cost of the supported project._
They don't, how do they want us to prove that?

registered to do business in CA an in good standing with CA Secretary of State
 have a current vendor number registered with LA county
 enroll in Direct Deposit
 have a DUNS number
_All SEE_

**Comment by nedventures** [comment]
@myamakerspace there's a sheet to fill out about it. 

There are links for all of those things to get done. I wouldn't rely on SEE if we can get it done. Whatever NEEDS to be done by them we can contact them.

**Comment by myamakerspace** [comment]
No i mean SEE already has those things and we have to ask them for theirs (DUNS number etc). We can't do it, because we are not the signatory entity.

**Comment by nedventures** [comment]
Okay, we can do this all first thing tomorrow morning.

**Comment by nedventures** [comment]
# Ned
- [x] add in due dates to calendar

**Comment by myamakerspace** [comment]
waiting on Alan's quote

**Comment by myamakerspace** [comment]
original budget https://lacounty.culturegrants.org/activeprograms/startapplication/cycle_id/12984/cycle_attempt/1/formset_id/6079/user_id/632312/page_id/4

**Comment by nedventures** [comment]
Sent.
