### ISSUE TITLE
Things we need in the office

### ISSUE THREAD

**Issue by myamakerspace** [LAMakerspace/ToDo#50]
For me to put things that pop into my head

Nice big sheets of paper for me to think things out on
Rainbows
Bookshelf
File cabinet
Beanbag
Lamp.
Art
3D printer so we can learn it
Plants
cat. imaginary cat
Whiteboard
Calendar
Joy

**Comment by nedventures** [comment]
Eain had mentioned that he could have us over to learn the basics of 3D printing. Now that I remembered, I'll go ahead and shoot him an e-mail about it.

**Comment by myamakerspace** [comment]
Cork Strips DIY:
http://www.homedit.com/diy-cork-notice-strip/

Cork Roll Source: 
http://www.hobbylobby.com/Crafts-Hobbies/Painting-Surfaces/Cork/2-Adhesive-Cork-Strip-Roll/p/137338

**Comment by nedventures** [comment]
Got shelf
Made calendar
got cork board
just need storage bins which will be done by next week.
