### ISSUE TITLE
Coding Crew Program Coordinator Job Description

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#86]
Leiny please write it up

Attaching examples.

@myamakerspace @nedventures please review
[https://docs.google.com/a/lamakerspace.com/document/d/1q3Uz7PmdJ7FDi0tpjS9skDNbSe2gAH26rJeKMAL_Rms/edit?usp=sharing](url)

**Comment by nedventures** [comment]
[Job Description Creative Computing Instructor PDF.pdf](https://github.com/LAMakerspace/ToDo/files/319267/Job.Description.Creative.Computing.Instructor.PDF.pdf)
[Job Description Creative Electronics and Robotics Instructor PDF.pdf](https://github.com/LAMakerspace/ToDo/files/319266/Job.Description.Creative.Electronics.and.Robotics.Instructor.PDF.pdf)
[Job Description Minecraft Instructor PDF.pdf](https://github.com/LAMakerspace/ToDo/files/319268/Job.Description.Minecraft.Instructor.PDF.pdf)

**Comment by myamakerspace** [comment]
Approved.

@nedventures please send to Heidi.

**Comment by nedventures** [comment]
Sent
